### ISSUE TITLE
Warnings from TMB

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#185]
Throw a warning to the R side in any of the following circumstances

- [x] any state variable is negative at any time in the simulation
- [x] eigenvector solution fails to converge
- [x] negative eigenvector elements
- [x] any element of the rate matrix is negative at any time

**Comment by guanwg** [comment]
All done!

**Comment by bbolker** [comment]
Should we have tests that exercise these warnings? (It's a little challenging, because by definition they involve pathological and possibly hard-to-replicate conditions ... if we come across any of these warnings actually getting thrown in production then we can turn around and construct minimal versions of them that also throw the warnings. Without that, it's hard to test if the warnings *aren't* getting thrown ...

Nonetheless I think we should probably close this (maybe add a new low-priority issue for implementing warnings when we can? Depends on one's priorities about having low-priority issues hanging around and cluttering up the board ...)

**Comment by stevencarlislewalker** [comment]
I agree that we need tests @bbolker, but my opinion is that we shouldn't close this yet.  Without tests this isn't done in my view.  I've generally tried to add tests for warnings/errors (e.g. https://github.com/mac-theobio/McMasterPandemic/blob/f5af0749ced3e7861be91fa5cd8ef6f1ca2bd3c1/tests/testthat/test-tmb.R#L674).

**Comment by stevencarlislewalker** [comment]
Tests:

- [ ] Lots of examples warning of negative state variables in `test-tmb.R` -- these were hidden before
- [ ] Eigenvector non-converge warning should be easy -- lower number of power iteration and/or raise tolerance
- [ ] Negative rate matrix should also be easy -- just add weird rates
