### ISSUE TITLE
Make a plan to pull out the computation of the indices on the R side

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#77]
- [x] Read https://github.com/mac-theobio/McMasterPandemic/commit/50d511e7fab 
- [x] Create first steps for pulling out the indices
- [x] Build broader plan
- [x] Define #78

**Comment by guanwg** [comment]
@stevencarlislewalker have you determined the data structure that would be passed through the interface from R to C++? Here is my half-baked proposal ...

According to https://github.com/mac-theobio/McMasterPandemic/blob/tmb/notes/indexing/indexing.md you wrote, the rate matrix R is calculated from parameters P plus x and y. Suppose the dimensions of the rate matrix is _m_ x _m_ and the length of parameter vector is _n_. Then, we can use a series of sparse matrices M_k (k=1, 2, ..., _n_) sized of _m_ x _m_ to define the x and y. 

- If M_k(i,j) = 0, then P(i) doesn't join the calculation of R(i,j)
- If M_k(i,j) = 1, then P(i) is multiplied into R(i,j)
- If M_k(i,j) = -1, then (1-P(i)) is multiplied into R(i,j)

With M_k(i,j) in place, we can update the rate matrix very efficiently in response to changesin parameters because we know what elements need to be updated if a specific parameter changes.

**Comment by stevencarlislewalker** [comment]
Plan is here: https://canmod.net/misc/flex_specs
